// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Toolbox.Data.DataContexts;

#nullable disable

namespace Toolbox.Data.Migrations
{
    [DbContext(typeof(InternalAppDbContext))]
    [Migration("20260203120000_AddAppInfoTutorialTracking")]
    partial class AddAppInfoTutorialTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Toolbox.Data.Common.AppInfo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentVersion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasCompletedTutorial")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IisRestartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastInstalledVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastShownChangelogForVersion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppInfo", null, t =>
                        {
                            t.HasCheckConstraint("CK_AppInfo_Singleton", "Id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentVersion = (string)null,
                            HasCompletedTutorial = false,
                            IisRestartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastInstalledVersion = (string)null,
                            LastShownChangelogForVersion = (string)null,
                            StartTime = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Toolbox.Data.Models.ShopSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShopYamlPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThemeFolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ToolboxSettingsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ToolboxSettingsId");

                    b.ToTable("ShopSettings");
                });

            modelBuilder.Entity("Toolbox.Data.Models.ShopYaml.DatabaseConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Encrypt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPoolSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TrustServerCertificate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShopDatabaseConnections");
                });

            modelBuilder.Entity("Toolbox.Data.Models.ToolboxSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowBetaUpdates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRefreshEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoRefreshSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BundleLogs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeleteAssetsOnShopRestart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeleteBundlerOnShopRestart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtensionsRepositoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneralFolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IisAppName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TfsApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("TfsProjectUrls")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnlySinceRestart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PinnedExtensionGroups")
                        .HasColumnType("TEXT");

                    b.Property<string>("PinnedThemeGroups")
                        .HasColumnType("TEXT");

                    b.Property<int>("RestartDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RestartShopOnThemeChange")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThemeRepositoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TrayIconIisSite")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings", null, t =>
                        {
                            t.HasCheckConstraint("CK_AppSettings_Singleton", "Id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowBetaUpdates = false,
                            AutoRefreshEnabled = false,
                            AutoRefreshSeconds = 60,
                            BundleLogs = false,
                            DeleteAssetsOnShopRestart = false,
                            DeleteBundlerOnShopRestart = false,
                            ExtensionsRepositoryPath = "C:\\Dev_Git\\Extensions",
                            GeneralFolderPath = "C:\\Dev_Git",
                            LogName = "4SELLERS",
                            TfsApiKey = "",
                            TfsProjectUrls = "",
                            OnlySinceRestart = true,
                            RestartDelaySeconds = 3,
                            RestartShopOnThemeChange = true,
                            ThemeRepositoryPath = "C:\\Dev_Git\\KundenThemes",
                            TrayIconIisSite = -9223372036854775808L
                        });
                });

            modelBuilder.Entity("Toolbox.Data.Models.ShopSetting", b =>
                {
                    b.HasOne("Toolbox.Data.Models.ToolboxSettings", "ToolboxSettings")
                        .WithMany("ShopSettingsList")
                        .HasForeignKey("ToolboxSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToolboxSettings");
                });

            modelBuilder.Entity("Toolbox.Data.Models.ToolboxSettings", b =>
                {
                    b.Navigation("ShopSettingsList");
                });
#pragma warning restore 612, 618
        }
    }
}

