using MudBlazor;

namespace Toolbox.Themes;

public static class Windows95Theme
{
    public static readonly MudTheme Theme = new()
    {
        PaletteLight = new PaletteLight
        {
            Primary = "#000080",
            PrimaryContrastText = "#ffffff",
            Secondary = "#c0c0c0",
            SecondaryContrastText = "#000000",
            Tertiary = "#c0c0c0",
            TertiaryContrastText = "#000000",
            Info = "#000080",
            InfoContrastText = "#ffffff",
            Success = "#008000",
            SuccessContrastText = "#ffffff",
            Warning = "#808000",
            WarningContrastText = "#ffffff",
            Error = "#800000",
            ErrorContrastText = "#ffffff",
            Dark = "#000000",
            DarkContrastText = "#ffffff",
            TextPrimary = "#000000",
            TextSecondary = "#000000",
            TextDisabled = "rgba(0,0,0,0.38)",
            ActionDefault = "#000000",
            ActionDisabled = "rgba(0,0,0,0.38)",
            ActionDisabledBackground = "rgba(0,0,0,0.12)",
            Background = "#c0c0c0",
            BackgroundGray = "#c0c0c0",
            Surface = "#c0c0c0",
            DrawerBackground = "#c0c0c0",
            DrawerText = "#000000",
            DrawerIcon = "#000000",
            AppbarBackground = "#000080",
            AppbarText = "#ffffff",
            LinesDefault = "#808080",
            LinesInputs = "#808080",
            TableLines = "#808080",
            TableStriped = "#dcdcdc",
            TableHover = "#dcdcdc",
            Divider = "#808080",
            DividerLight = "#ffffff",
            PrimaryDarken = "#00006a",
            PrimaryLighten = "#3a3aa0",
            SecondaryDarken = "#a0a0a0",
            SecondaryLighten = "#ffffff",
            GrayDefault = "#808080",
            GrayLight = "#c0c0c0",
            GrayLighter = "#dcdcdc",
            GrayDark = "#606060",
            GrayDarker = "#404040",
            HoverOpacity = 0.06,
            RippleOpacity = 0.1,
            RippleOpacitySecondary = 0.2,
        },
        PaletteDark = new PaletteDark
        {
            Primary = "#000080",
            PrimaryContrastText = "#ffffff",
            Secondary = "#c0c0c0",
            SecondaryContrastText = "#000000",
            Tertiary = "#c0c0c0",
            TertiaryContrastText = "#000000",
            Info = "#000080",
            InfoContrastText = "#ffffff",
            Success = "#008000",
            SuccessContrastText = "#ffffff",
            Warning = "#808000",
            WarningContrastText = "#ffffff",
            Error = "#800000",
            ErrorContrastText = "#ffffff",
            Dark = "#000000",
            DarkContrastText = "#ffffff",
            TextPrimary = "#000000",
            TextSecondary = "#000000",
            TextDisabled = "rgba(0,0,0,0.38)",
            ActionDefault = "#000000",
            ActionDisabled = "rgba(0,0,0,0.38)",
            ActionDisabledBackground = "rgba(0,0,0,0.12)",
            Background = "#c0c0c0",
            BackgroundGray = "#c0c0c0",
            Surface = "#c0c0c0",
            DrawerBackground = "#c0c0c0",
            DrawerText = "#000000",
            DrawerIcon = "#000000",
            AppbarBackground = "#000080",
            AppbarText = "#ffffff",
            LinesDefault = "#808080",
            LinesInputs = "#808080",
            TableLines = "#808080",
            TableStriped = "#dcdcdc",
            Divider = "#808080",
            DividerLight = "#ffffff",
            GrayDefault = "#808080",
            GrayLight = "#c0c0c0",
            GrayLighter = "#dcdcdc",
            GrayDark = "#606060",
            GrayDarker = "#404040",
        },
        LayoutProperties = new LayoutProperties
        {
            DefaultBorderRadius = "0px",
            DrawerMiniWidthLeft = "56px",
            DrawerMiniWidthRight = "56px",
            DrawerWidthLeft = "240px",
            DrawerWidthRight = "240px",
            AppbarHeight = "64px",
        },
        Typography = new Typography
        {
            Default = new DefaultTypography
            {
                FontFamily = ["W95FA", "Tahoma", "Arial", "sans-serif"],
                FontWeight = "400",
                FontSize = ".875rem",
                LineHeight = "1.4",
                LetterSpacing = "0",
                TextTransform = "none",
            },
            Button = new ButtonTypography
            {
                FontFamily = ["W95FA", "Tahoma", "Arial", "sans-serif"],
                FontWeight = "400",
                FontSize = ".875rem",
                LineHeight = "1.2",
                LetterSpacing = "0",
                TextTransform = "none",
            },
        },
        ZIndex = new ZIndex
        {
            Drawer = 1100,
            Popover = 1200,
            AppBar = 1300,
            Dialog = 1400,
            Snackbar = 1500,
            Tooltip = 1600,
        },
    };
}
