name: Build and Attach Release

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish self-contained EXE
        run: |
          dotnet publish Benjis-Shop-Toolbox/Benjis-Shop-Toolbox.csproj \
            -c Release -r win-x64 --self-contained \
            -p:PublishSingleFile=true \
            -o publish

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: publish/Benjis-Shop-Toolbox.exe
